spring:
  application:
    name: spring-security-jwt

  threads:
    virtual:
      enabled: true

  datasource:
    username: Thong
    password: qwerqwer
    url: jdbc:postgresql://localhost:2025/jwt_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.example.security: INFO
    org.springframework.security: DEBUG
